/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/layouts/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    color: {
      black: 'var(--black)',
      white: 'var(--white)',
      'black-alpha-05': 'var(--black-alpha-05)',
      'black-alpha-10': 'var(--black-alpha-10)',
      'black-alpha-15': 'var(--black-alpha-15)',
      'black-alpha-20': 'var(--black-alpha-20)',
      'black-alpha-30': 'var(--black-alpha-30)',
      'black-alpha-40': 'var(--black-alpha-40)',
      'black-alpha-50': 'var(--black-alpha-50)',
      'black-alpha-60': 'var(--black-alpha-60)',
      'black-alpha-70': 'var(--black-alpha-80)',
      'blue-05': 'var(--blue-05)',
      'blue-30': 'var(--blue-30)',
      'blue-40': 'var(--blue-40)',
      'blue-60': 'var(--blue-60)',
      'blue-70': 'var(--blue-70)',
      'blue-80': 'var(--blue-80)',
      'button-text': 'var(--button-text)',
      'comment-background': 'var(--comment-background)',
      'dark-mode-gray-35': 'var(--dark-mode-gray-35)',
      'dark-mode-gray-50': 'var(--dark-mode-gray-50)',
      'dark-mode-gray-70': 'var(--dark-mode-gray-70)',
      'dark-mode-gray-80': 'var(--dark-mode-gray-80)',
      'dark-mode-gray-90': 'var(--dark-mode-gray-90)',
      'dark-mode-gray-100': 'var(--dark-mode-gray-100)',
      'gray-00': 'var(--gray-00)',
      'gray-05': 'var(--gray-05)',
      'gray-10': 'var(--gray-10)',
      'gray-20': 'var(--gray-20)',
      'gray-25': 'var(--gray-25)',
      'gray-30': 'var(--gray-30)',
      'gray-45': 'var(--gray-45)',
      'gray-70': 'var(--gray-70)',
      'gray-80': 'var(--gray-80)',
      'gray-90': 'var(--gray-90)',
      'gray-100': 'var(--gray-100)',
      'green-55': 'var(--green-55)',
      highlight: 'var(--highlight)',
      'highlight-cell-background': 'var(--highlight-cell-background)',
      'primary-icon': 'var(--primary-icon)',
      'primary-text': 'var(--primary-text)',
      'red-55': 'var(--red-55)',
      soft: 'var(--soft)',
      'spectrum-aluminum-tint-70': 'var(--spectrum-aluminum-tint-70)',
      'spectrum-blue-gray-tint-70': 'var(--spectrum-blue-gray-tint-70)',
      'spectrum-cherry': 'var(--spectrum-cherry)',
      'spectrum-cherry-tint-70': 'var(--spectrum-cherry-tint-70)',
      'spectrum-grape-tint-70': 'var(--spectrum-grape-tint-70)',
      'spectrum-grape-tint-90': 'var(--spectrum-grape-tint-90)',
      'spectrum-lemon-dark-1': 'var(--spectrum-lemon-dark-1)',
      'spectrum-lemon-tint-70': 'var(--spectrum-lemon-tint-70)',
      'spectrum-lime': 'var(--spectrum-lime)',
      'spectrum-lime-tint-70': 'var(--spectrum-lime-tint-70)',
      'spectrum-orange-tint-70': 'var(--spectrum-orange-tint-70)',
      'spectrum-orange-tint-90': 'var(--spectrum-orange-tint-90)',
      'spectrum-seafoam-tint-70': 'var(--spectrum-seafoam-tint-70)',
      'spectrum-slate-dark-2': 'var(--spectrum-slate-dark-2)',
      'spectrum-slate-tint-70': 'var(--spectrum-slate-tint-70)',
      'spectrum-teal': 'var(--spectrum-teal)',
      'spectrum-teal-dark-1': 'var(--spectrum-teal-dark-1)',
      'spectrum-teal-dark-2': 'var(--spectrum-teal-dark-2)',
      'spectrum-teal-tint-70': 'var(--spectrum-teal-tint-70)',
      'spectrum-teal-tint-90': 'var(--spectrum-teal-tint-90)',
      'spectrum-tomato': 'var(--spectrum-tomato)',
      'spectrum-tomato-tint-30': 'var(--spectrum-tomato-tint-30)',
      'spectrum-tomato-tint-90': 'var(--spectrum-tomato-tint-90)',

      'base-blue': 'var(--base-blue)',
      'base-cherry': 'var(--base-cherry)',
      'base-grape': 'var(--base-grape)',
      'base-lemon': 'var(--base-lemon)',
      'base-lime': 'var(--base-lime)',
      'base-pink': 'var(--base-pink)',
      'base-seafoam': 'var(--base-seafoam)',
      'base-teal': 'var(--base-teal)',
      'base-tomato': 'var(--base-tomato)',
    },
  },
  plugins: [],
}
